# Generated by Django 4.2.15 on 2024-09-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseeker')),
                ('requested_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposition')),
            ],
        ),
    ]
